card_name:
  db:
    - 东楼经理室
    - 变电站技术室
    - 西楼调控房
    - 西楼监视室
    - 售票办公室
    - 军营保管室
    - 设备领用室
    - 水泥厂宿舍201
    - 中心贵宾室
    - 水泥厂办公室
    - 地下通道钥匙
    - 西楼医务室
    - 变电站宿舍
    - 实验楼资料室
  cg:
    - 酒店国王房
    - 雷达站无人机平台
    - 酒店王子房
    - 雷达站数据中心
    - 实验楼资料室
    - 酒店黑桃房
    - 雷达站控制室
    - 实验楼办公室
    - 酒店将军房
    - 酒店方片房
    - 小镇餐厅
    - 运输机会议室

coordinate_position:
  standard_screen_pixel: [2560, 1440]
  card_region: [583, 208]
  card_pixel: [625, 212]
  name_pixel: [178, 27]
  price_region: [2184, 1172]
  price_pixel: [116, 23]